Repository pasqal-io/pyqtorch, pull requests merged in 2024-07, with the labels that each got.

#212 [Fix] Overload `to` method of pyq.Scale
  pyqtorch/analog.py
Labels: bug, feature

#213 [Feature] Single gap GPSR
  docs/differentiation.md
  pyqtorch/api.py
  pyqtorch/gpsr.py
  pyqtorch/utils.py
  tests/test_circuit.py
Labels: feature

#218 [Bug] Fix GPSR with repeated params
  pyqtorch/gpsr.py
  tests/test_circuit.py
Labels: bug

#219 [Bug] Fix GPSR with repeated params
  pyqtorch/gpsr.py
  tests/test_circuit.py
Labels: bug

#205 [Refactoring, Hamevo] Optimize block_to_tensor calls for repeated execution of HamEvo
  pyqtorch/analog.py
  tests/test_analog.py
Labels: Refactor

#223 [Refactor] Add eigenvals_generator for parametric operations
  pyproject.toml
  pyqtorch/parametric.py
  pyqtorch/primitive.py
  tests/test_digital.py
Labels: feature, Refactor

#233 [Bug] Fix check support PSR
  pyqtorch/gpsr.py
  tests/test_differentiation.py
Labels: bug

#234 [Testing] Increase cross-platform embedding atol
  pyqtorch/utils.py
  tests/test_embedding.py
Labels: bug

#186 [Feature] Density matrix partial trace
  pyqtorch/utils.py
  tests/test_digital.py
Labels: feature, noise

#237 [Documentation] Add a note about units
  docs/analog.md
  docs/index.md
  pyqtorch/analog.py
Labels: documentation

#222 [Feature] Add multi gap GPSR
  docs/differentiation.md
  pyproject.toml
  pyqtorch/gpsr.py
  pyqtorch/parametric.py
  pyqtorch/utils.py
  tests/test_differentiation.py
  tests/test_gpsr.py
Labels: feature

#187 [Feature] Quantum dropout
  docs/dropout.md
  pyproject.toml
  pyqtorch/__init__.py
  pyqtorch/circuit.py
  pyqtorch/utils.py
  tests/test_dropout.py
Labels: feature

#220 [Bug, Refactor, Testing] Fix tensor logic, change Observable and Scale, add more tests
  docs/differentiation.md
  docs/dropout.md
  docs/embed.md
  docs/fitting_a_function.md
  docs/index.md
  docs/pde.md
  pyqtorch/__init__.py
  pyqtorch/adjoint.py
  pyqtorch/analog.py
  pyqtorch/api.py
  pyqtorch/bitstrings.py
  pyqtorch/circuit.py
  pyqtorch/embed.py
  pyqtorch/gpsr.py
  pyqtorch/parametric.py
  pyqtorch/primitive.py
  pyqtorch/utils.py
  tests/conftest.py
  tests/helpers.py
  tests/test_analog.py
  tests/test_differentiation.py
  tests/test_digital.py
  tests/test_dropout.py
  tests/test_embedding.py
  tests/test_gpsr.py
  tests/test_tensor.py
Labels: bug, Refactor, testing

#239 [Feature] Add finite shots expectation value
  pyqtorch/api.py
  pyqtorch/circuit.py
  pyqtorch/gpsr.py
  pyqtorch/primitive.py
  pyqtorch/utils.py
  tests/helpers.py
  tests/test_differentiation.py
  tests/test_embedding.py
  tests/test_gpsr.py
Labels: feature

#242 [Refact] Optimize permute_basis function
  pyqtorch/bitstrings.py
  pyqtorch/primitive.py
  pyqtorch/utils.py
  tests/test_gpsr.py
Labels: Refactor

#243 [Refactor] Minor improvements to type annotations and initialisations.
  pyqtorch/embed.py
Labels: Refactor
