Repository pasqal-io/pyqtorch, pull requests merged in 2024-06, with the labels that each got.

#185 [Refac] Remove batch_first and batch_last functions
  pyqtorch/utils.py
Labels: Refactor, noise

#182 [Refactor] Correct behaviour of CSWAP constructor
  pyqtorch/parametric.py
  pyqtorch/primitive.py
  tests/test_circuit.py
  tests/test_digital.py
Labels: bug

#174 [Feature | Refac] Add Tensor method & Symbolic HamiltonianEvolution
  docs/index.md
  pyproject.toml
  pyqtorch/__init__.py
  pyqtorch/adjoint.py
  pyqtorch/analog.py
  pyqtorch/apply.py
  pyqtorch/circuit.py
  pyqtorch/matrices.py
  pyqtorch/noise.py
  pyqtorch/parametric.py
  pyqtorch/primitive.py
  pyqtorch/utils.py
  tests/conftest.py
  tests/test_analog.py
  tests/test_circuit.py
  tests/test_digital.py
Labels: feature, Refactor

#194 [Documentation] Restructure docs in files
  docs/adjoint.md
  docs/cuda_debugging.md
  docs/dropout.md
  docs/fitting_a_function.md
  docs/index.md
  docs/noise.md
  docs/pde.md
  mkdocs.yml
Labels: documentation

#195 [Fix] Docs display
  docs/adjoint.md
  docs/extras/css/colors.css
  docs/extras/css/home.css
  docs/extras/css/mkdocstrings.css
  docs/extras/javascripts/mathjax.js
  docs/extras/overrides/home.html
  docs/index.md
  docs/noise.md
  mkdocs.yml
Labels: bug

#198 [Feature] Add run, sample and from_bitstring
  pyproject.toml
  pyqtorch/__init__.py
  pyqtorch/circuit.py
  tests/test_circuit.py
Labels: feature

#204 [Fix] Handle nested param dicts
  pyproject.toml
  pyqtorch/circuit.py
  tests/test_circuit.py
Labels: bug

#206 [Feature] Allow constant parameters in ParametricGate
  pyproject.toml
  pyqtorch/adjoint.py
  pyqtorch/parametric.py
  tests/test_digital.py
Labels: feature
