Repository pasqal-io/pyqtorch, pull requests merged in 2024-08, with the labels that each got.

#246 [Refact] Consistent base classes
  pyproject.toml
  pyqtorch/adjoint.py
  pyqtorch/analog.py
  pyqtorch/circuit.py
  pyqtorch/matrices.py
  pyqtorch/parametric.py
  pyqtorch/primitive.py
  pyqtorch/quantum_ops.py
  pyqtorch/utils.py
  tests/test_digital.py
Labels: Refactor, breaking

#254 [Infra] Harmonise infra
  pyproject.toml
Labels: infra

#256 [Infra] Harmonise infra
  .github/workflows/lint.yml
  .github/workflows/test.yml
  pyproject.toml
Labels: infra

#257 [Refactor] Update badge.
  README.md
Labels: Refactor

#253 [Refact] Module reorganization
  docs/dropout.md
  docs/fitting_a_function.md
  docs/noise.md
  docs/pde.md
  pyqtorch/__init__.py
  pyqtorch/api.py
  pyqtorch/circuit.py
  pyqtorch/composite/__init__.py
  pyqtorch/composite/compose.py
  pyqtorch/composite/sequence.py
  pyqtorch/differentiation/adjoint.py
  pyqtorch/differentiation/gpsr.py
  pyqtorch/hamiltonians/__init__.py
  pyqtorch/hamiltonians/evolution.py
  pyqtorch/hamiltonians/observable.py
  pyqtorch/noise/__init__.py
  pyqtorch/noise/gates.py
  pyqtorch/noise/protocol.py
  pyqtorch/primitives/__init__.py
  pyqtorch/primitives/parametric.py
  pyqtorch/primitives/parametric_gates.py
  pyqtorch/primitives/primitive.py
  pyqtorch/primitives/primitive_gates.py
  pyqtorch/quantum_operation.py
  pyqtorch/utils.py
  tests/conftest.py
  tests/helpers.py
  tests/test_analog.py
  tests/test_circuit.py
  tests/test_differentiation.py
  tests/test_digital.py
  tests/test_embedding.py
  tests/test_gpsr.py
  tests/test_noise.py
  tests/test_tensor.py
Labels: Refactor

#255 [Feature] HamiltonianEvolution supported in GPSR with fixed generators
  docs/differentiation.md
  pyqtorch/differentiation/gpsr.py
  pyqtorch/hamiltonians/evolution.py
  pyqtorch/matrices.py
  pyqtorch/quantum_operation.py
  pyqtorch/utils.py
  tests/test_gpsr.py
Labels: feature

#259 [Bugfix] Adjust shift with hamevo via a prefactor
  pyqtorch/differentiation/gpsr.py
Labels: bug

#260 [Bugfix] Divide shift by spectral gap for single-gap PSR
  pyqtorch/differentiation/gpsr.py
Labels: bug

#261 [Feature] Extend hamevo initialization to single parametric gates
  pyqtorch/hamiltonians/evolution.py
Labels: feature

#265 [Feature] Add jacobian method for adjoint supporting hamevo
  pyqtorch/differentiation/adjoint.py
  pyqtorch/hamiltonians/evolution.py
  pyqtorch/utils.py
  tests/test_differentiation.py
Labels: feature

#268 [Performance, Refactor] Operator multiplication without explicit identities
  pyqtorch/apply.py
  pyqtorch/noise/gates.py
  pyqtorch/quantum_operation.py
  tests/test_noise.py
  tests/test_tensor.py
Labels: performance, Refactor, noise

#269 [Feature] Add issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new-feature.yml
  pyproject.toml
Labels: feature

#270 [BugFix] Avoid reduce with empty operations
  pyqtorch/composite/sequence.py
Labels: bug
