Repository pasqal-io/pyqtorch, pull requests merged in 2024-11, with the labels that each got.

#289 [Release] Bump version to 1.5.1
  pyproject.toml
Labels: release

#291 [Feature] Allow time-dependent duration to be passed at runtime
  pyproject.toml
  pyqtorch/hamiltonians/evolution.py
  tests/test_analog.py
Labels: feature

#294 [Feature] Add batch dimension to input states for time-dependent solvers
  docs/time_dependent.md
  pyqtorch/hamiltonians/evolution.py
  pyqtorch/time_dependent/integrators/adaptive.py
  pyqtorch/time_dependent/integrators/krylov.py
  pyqtorch/time_dependent/mesolve.py
  pyqtorch/time_dependent/methods/dp5.py
  pyqtorch/time_dependent/options.py
  pyqtorch/time_dependent/sesolve.py
  pyqtorch/time_dependent/solvers.py
  tests/test_analog.py
  tests/test_solvers.py
Labels: feature

#297 [Bugfix] Changing shift interval for multigap GGPSR
  pyqtorch/differentiation/gpsr.py
  tests/test_analog.py
Labels: bug

#296 [Feature] Correlated readout and extending ReadoutNoise
  .github/workflows/test.yml
  docs/noise.md
  pyqtorch/api.py
  pyqtorch/circuit.py
  pyqtorch/noise/__init__.py
  pyqtorch/noise/readout.py
  tests/test_readout.py
Labels: feature
