Repository pasqal-io/pyqtorch, pull requests merged in 2025-01, with the labels that each got.

#307 [Bugfix] Support density matrices for sampled expectation
  pyqtorch/api.py
  tests/test_differentiation.py
Labels: bug

#308 [Bugfix] Fix mean when empty tensor for readout
  pyqtorch/noise/readout.py
  tests/test_readout.py
Labels: bug

#309 [Docs] Add coverage badge to PyQTorch.
  .github/workflows/test.yml
  README.md
  pyproject.toml
Labels: documentation, infra

#310 [Docs] Delete unnecessary line as coverage should be automated.
  .github/workflows/test.yml
  pyproject.toml
Labels: documentation
