Repository pasqal-io/pyqtorch, pull requests merged in 2025-03, with the labels that each got.

#314 [Release] Bump to 1.7.1
  pyproject.toml
Labels: release

#315 [Feature] GPSR with repeated parameters
  pyqtorch/differentiation/gpsr.py
  pyqtorch/hamiltonians/evolution.py
  pyqtorch/primitives/parametric.py
  pyqtorch/quantum_operation.py
  tests/differentiation/test_differentiation.py
  tests/differentiation/test_gpsr.py
  tests/helpers.py
Labels: feature

#316 [Release] 1.7.2
  pyproject.toml
  pyqtorch/utils.py
Labels: release

#317 [Feature] Update python to 3.13
  .github/workflows/test.yml
  pyproject.toml
Labels: feature

#321 [Feature] Mutated single-qubit gates
  pyproject.toml
  pyqtorch/primitives/mutation_utils.py
  pyqtorch/primitives/primitive.py
  pyqtorch/primitives/primitive_gates.py
  tests/differentiation/test_gpsr.py
  tests/primitives/test_digital.py
Labels: feature

#322 [Bugfix] Clone state in mutable N
  pyqtorch/primitives/primitive_gates.py
Labels: bug
